package com.tlv8.doc.clt.pojo;

import java.io.Serializable;
import java.util.Date;

public class SaDocnode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.sid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.sparentid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String sparentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.sdocname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String sdocname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.ssequence
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String ssequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.ssize
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private Double ssize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.skind
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String skind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.sdocpath
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String sdocpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.sdocdisplaypath
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String sdocdisplaypath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.screatorfid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String screatorfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.screatorname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String screatorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.screatordeptname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String screatordeptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.screatetime
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private Date screatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.seditorfid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String seditorfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.seditorname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String seditorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.seditordeptname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String seditordeptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.slastwriterfid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String slastwriterfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.slastwritername
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String slastwritername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.slastwriterdeptname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String slastwriterdeptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.slastwritetime
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private Date slastwritetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.sfileid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String sfileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.sdescription
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String sdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.sdocliveversionid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private Integer sdocliveversionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.sclassification
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String sclassification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.skeywords
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String skeywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.sdocserialnumber
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String sdocserialnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.snamespace
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String snamespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.scachename
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String scachename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.srevisioncachename
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private String srevisioncachename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.sflag
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private Integer sflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnode.version
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa_docnode
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.sid
     *
     * @return the value of sa_docnode.sid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.sid
     *
     * @param sid the value for sa_docnode.sid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.sparentid
     *
     * @return the value of sa_docnode.sparentid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSparentid() {
        return sparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.sparentid
     *
     * @param sparentid the value for sa_docnode.sparentid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSparentid(String sparentid) {
        this.sparentid = sparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.sdocname
     *
     * @return the value of sa_docnode.sdocname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSdocname() {
        return sdocname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.sdocname
     *
     * @param sdocname the value for sa_docnode.sdocname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSdocname(String sdocname) {
        this.sdocname = sdocname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.ssequence
     *
     * @return the value of sa_docnode.ssequence
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSsequence() {
        return ssequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.ssequence
     *
     * @param ssequence the value for sa_docnode.ssequence
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSsequence(String ssequence) {
        this.ssequence = ssequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.ssize
     *
     * @return the value of sa_docnode.ssize
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public Double getSsize() {
        return ssize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.ssize
     *
     * @param ssize the value for sa_docnode.ssize
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSsize(Double ssize) {
        this.ssize = ssize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.skind
     *
     * @return the value of sa_docnode.skind
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSkind() {
        return skind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.skind
     *
     * @param skind the value for sa_docnode.skind
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSkind(String skind) {
        this.skind = skind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.sdocpath
     *
     * @return the value of sa_docnode.sdocpath
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSdocpath() {
        return sdocpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.sdocpath
     *
     * @param sdocpath the value for sa_docnode.sdocpath
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSdocpath(String sdocpath) {
        this.sdocpath = sdocpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.sdocdisplaypath
     *
     * @return the value of sa_docnode.sdocdisplaypath
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSdocdisplaypath() {
        return sdocdisplaypath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.sdocdisplaypath
     *
     * @param sdocdisplaypath the value for sa_docnode.sdocdisplaypath
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSdocdisplaypath(String sdocdisplaypath) {
        this.sdocdisplaypath = sdocdisplaypath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.screatorfid
     *
     * @return the value of sa_docnode.screatorfid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getScreatorfid() {
        return screatorfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.screatorfid
     *
     * @param screatorfid the value for sa_docnode.screatorfid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setScreatorfid(String screatorfid) {
        this.screatorfid = screatorfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.screatorname
     *
     * @return the value of sa_docnode.screatorname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getScreatorname() {
        return screatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.screatorname
     *
     * @param screatorname the value for sa_docnode.screatorname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setScreatorname(String screatorname) {
        this.screatorname = screatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.screatordeptname
     *
     * @return the value of sa_docnode.screatordeptname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getScreatordeptname() {
        return screatordeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.screatordeptname
     *
     * @param screatordeptname the value for sa_docnode.screatordeptname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setScreatordeptname(String screatordeptname) {
        this.screatordeptname = screatordeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.screatetime
     *
     * @return the value of sa_docnode.screatetime
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public Date getScreatetime() {
        return screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.screatetime
     *
     * @param screatetime the value for sa_docnode.screatetime
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setScreatetime(Date screatetime) {
        this.screatetime = screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.seditorfid
     *
     * @return the value of sa_docnode.seditorfid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSeditorfid() {
        return seditorfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.seditorfid
     *
     * @param seditorfid the value for sa_docnode.seditorfid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSeditorfid(String seditorfid) {
        this.seditorfid = seditorfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.seditorname
     *
     * @return the value of sa_docnode.seditorname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSeditorname() {
        return seditorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.seditorname
     *
     * @param seditorname the value for sa_docnode.seditorname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSeditorname(String seditorname) {
        this.seditorname = seditorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.seditordeptname
     *
     * @return the value of sa_docnode.seditordeptname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSeditordeptname() {
        return seditordeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.seditordeptname
     *
     * @param seditordeptname the value for sa_docnode.seditordeptname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSeditordeptname(String seditordeptname) {
        this.seditordeptname = seditordeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.slastwriterfid
     *
     * @return the value of sa_docnode.slastwriterfid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSlastwriterfid() {
        return slastwriterfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.slastwriterfid
     *
     * @param slastwriterfid the value for sa_docnode.slastwriterfid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSlastwriterfid(String slastwriterfid) {
        this.slastwriterfid = slastwriterfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.slastwritername
     *
     * @return the value of sa_docnode.slastwritername
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSlastwritername() {
        return slastwritername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.slastwritername
     *
     * @param slastwritername the value for sa_docnode.slastwritername
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSlastwritername(String slastwritername) {
        this.slastwritername = slastwritername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.slastwriterdeptname
     *
     * @return the value of sa_docnode.slastwriterdeptname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSlastwriterdeptname() {
        return slastwriterdeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.slastwriterdeptname
     *
     * @param slastwriterdeptname the value for sa_docnode.slastwriterdeptname
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSlastwriterdeptname(String slastwriterdeptname) {
        this.slastwriterdeptname = slastwriterdeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.slastwritetime
     *
     * @return the value of sa_docnode.slastwritetime
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public Date getSlastwritetime() {
        return slastwritetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.slastwritetime
     *
     * @param slastwritetime the value for sa_docnode.slastwritetime
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSlastwritetime(Date slastwritetime) {
        this.slastwritetime = slastwritetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.sfileid
     *
     * @return the value of sa_docnode.sfileid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSfileid() {
        return sfileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.sfileid
     *
     * @param sfileid the value for sa_docnode.sfileid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSfileid(String sfileid) {
        this.sfileid = sfileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.sdescription
     *
     * @return the value of sa_docnode.sdescription
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSdescription() {
        return sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.sdescription
     *
     * @param sdescription the value for sa_docnode.sdescription
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSdescription(String sdescription) {
        this.sdescription = sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.sdocliveversionid
     *
     * @return the value of sa_docnode.sdocliveversionid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public Integer getSdocliveversionid() {
        return sdocliveversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.sdocliveversionid
     *
     * @param sdocliveversionid the value for sa_docnode.sdocliveversionid
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSdocliveversionid(Integer sdocliveversionid) {
        this.sdocliveversionid = sdocliveversionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.sclassification
     *
     * @return the value of sa_docnode.sclassification
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSclassification() {
        return sclassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.sclassification
     *
     * @param sclassification the value for sa_docnode.sclassification
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSclassification(String sclassification) {
        this.sclassification = sclassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.skeywords
     *
     * @return the value of sa_docnode.skeywords
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSkeywords() {
        return skeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.skeywords
     *
     * @param skeywords the value for sa_docnode.skeywords
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSkeywords(String skeywords) {
        this.skeywords = skeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.sdocserialnumber
     *
     * @return the value of sa_docnode.sdocserialnumber
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSdocserialnumber() {
        return sdocserialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.sdocserialnumber
     *
     * @param sdocserialnumber the value for sa_docnode.sdocserialnumber
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSdocserialnumber(String sdocserialnumber) {
        this.sdocserialnumber = sdocserialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.snamespace
     *
     * @return the value of sa_docnode.snamespace
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSnamespace() {
        return snamespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.snamespace
     *
     * @param snamespace the value for sa_docnode.snamespace
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSnamespace(String snamespace) {
        this.snamespace = snamespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.scachename
     *
     * @return the value of sa_docnode.scachename
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getScachename() {
        return scachename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.scachename
     *
     * @param scachename the value for sa_docnode.scachename
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setScachename(String scachename) {
        this.scachename = scachename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.srevisioncachename
     *
     * @return the value of sa_docnode.srevisioncachename
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public String getSrevisioncachename() {
        return srevisioncachename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.srevisioncachename
     *
     * @param srevisioncachename the value for sa_docnode.srevisioncachename
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSrevisioncachename(String srevisioncachename) {
        this.srevisioncachename = srevisioncachename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.sflag
     *
     * @return the value of sa_docnode.sflag
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public Integer getSflag() {
        return sflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.sflag
     *
     * @param sflag the value for sa_docnode.sflag
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setSflag(Integer sflag) {
        this.sflag = sflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnode.version
     *
     * @return the value of sa_docnode.version
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnode.version
     *
     * @param version the value for sa_docnode.version
     *
     * @mbg.generated Wed Apr 19 15:03:33 CST 2023
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}