package com.tlv8.doc.clt.pojo;

import java.io.Serializable;

public class SaDocnamespace implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnamespace.sid
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnamespace.sdisplayname
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    private String sdisplayname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnamespace.shost
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    private String shost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnamespace.sport
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    private Integer sport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnamespace.surl
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    private String surl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnamespace.sflag
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    private Integer sflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnamespace.shtths
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    private String shtths;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_docnamespace.version
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa_docnamespace
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnamespace.sid
     *
     * @return the value of sa_docnamespace.sid
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnamespace.sid
     *
     * @param sid the value for sa_docnamespace.sid
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnamespace.sdisplayname
     *
     * @return the value of sa_docnamespace.sdisplayname
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public String getSdisplayname() {
        return sdisplayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnamespace.sdisplayname
     *
     * @param sdisplayname the value for sa_docnamespace.sdisplayname
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public void setSdisplayname(String sdisplayname) {
        this.sdisplayname = sdisplayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnamespace.shost
     *
     * @return the value of sa_docnamespace.shost
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public String getShost() {
        return shost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnamespace.shost
     *
     * @param shost the value for sa_docnamespace.shost
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public void setShost(String shost) {
        this.shost = shost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnamespace.sport
     *
     * @return the value of sa_docnamespace.sport
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public Integer getSport() {
        return sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnamespace.sport
     *
     * @param sport the value for sa_docnamespace.sport
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public void setSport(Integer sport) {
        this.sport = sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnamespace.surl
     *
     * @return the value of sa_docnamespace.surl
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public String getSurl() {
        return surl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnamespace.surl
     *
     * @param surl the value for sa_docnamespace.surl
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public void setSurl(String surl) {
        this.surl = surl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnamespace.sflag
     *
     * @return the value of sa_docnamespace.sflag
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public Integer getSflag() {
        return sflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnamespace.sflag
     *
     * @param sflag the value for sa_docnamespace.sflag
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public void setSflag(Integer sflag) {
        this.sflag = sflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnamespace.shtths
     *
     * @return the value of sa_docnamespace.shtths
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public String getShtths() {
        return shtths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnamespace.shtths
     *
     * @param shtths the value for sa_docnamespace.shtths
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public void setShtths(String shtths) {
        this.shtths = shtths;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_docnamespace.version
     *
     * @return the value of sa_docnamespace.version
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_docnamespace.version
     *
     * @param version the value for sa_docnamespace.version
     *
     * @mbg.generated Wed Apr 19 17:51:21 CST 2023
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}