package com.tlv8.oa.mapper;

import com.tlv8.oa.pojo.OaNewsRelease;
import java.util.List;

public interface OaNewsReleaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_release
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int deleteByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_release
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int insert(OaNewsRelease row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_release
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    OaNewsRelease selectByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_release
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    List<OaNewsRelease> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_release
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int updateByPrimaryKey(OaNewsRelease row);
}