package com.tlv8.oa.mapper;

import com.tlv8.oa.pojo.OaNewsCount;
import java.util.List;

public interface OaNewsCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_count
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int deleteByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_count
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int insert(OaNewsCount row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_count
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    OaNewsCount selectByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_count
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    List<OaNewsCount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_count
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int updateByPrimaryKey(OaNewsCount row);
}