package com.tlv8.oa.mapper;

import com.tlv8.oa.pojo.OaNewsColumn;
import java.util.List;

public interface OaNewsColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_column
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int deleteByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_column
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int insert(OaNewsColumn row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_column
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    OaNewsColumn selectByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_column
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    List<OaNewsColumn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_column
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int updateByPrimaryKey(OaNewsColumn row);
}