package com.tlv8.oa.mapper;

import com.tlv8.oa.pojo.OaNewsOpen;
import java.util.List;

public interface OaNewsOpenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_open
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int deleteByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_open
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int insert(OaNewsOpen row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_open
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    OaNewsOpen selectByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_open
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    List<OaNewsOpen> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_news_open
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    int updateByPrimaryKey(OaNewsOpen row);
}