package com.tlv8.oa.mapper;

import com.tlv8.oa.pojo.OaNoticePerson;
import java.util.List;
import java.util.Map;

public interface OaNoticePersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice_person
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    int deleteByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice_person
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    int insert(OaNoticePerson row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice_person
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    OaNoticePerson selectByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice_person
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    List<OaNoticePerson> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_notice_person
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    int updateByPrimaryKey(OaNoticePerson row);
    
    List<OaNoticePerson> selectByMainid(String fmainid);
    
    List<OaNoticePerson> selectByMainidPersonID(Map<String, String> param);
}