package com.tlv8.oa.mapper;

import com.tlv8.oa.pojo.OaPulicnotice;
import java.util.List;
import java.util.Map;

public interface OaPulicnoticeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table oa_pulicnotice
	 *
	 * @mbg.generated Wed Mar 20 19:07:18 CST 2024
	 */
	int deleteByPrimaryKey(String fid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table oa_pulicnotice
	 *
	 * @mbg.generated Wed Mar 20 19:07:18 CST 2024
	 */
	int insert(OaPulicnotice row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table oa_pulicnotice
	 *
	 * @mbg.generated Wed Mar 20 19:07:18 CST 2024
	 */
	OaPulicnotice selectByPrimaryKey(String fid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table oa_pulicnotice
	 *
	 * @mbg.generated Wed Mar 20 19:07:18 CST 2024
	 */
	List<OaPulicnotice> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table oa_pulicnotice
	 *
	 * @mbg.generated Wed Mar 20 19:07:18 CST 2024
	 */
	int updateByPrimaryKey(OaPulicnotice row);

	Map<String, Object> selectPortalNotesCount(String fpersonid);
}