package com.tlv8.flw.mapper;

import com.tlv8.flw.pojo.SaFlowdrawlg;
import java.util.List;

public interface SaFlowdrawlgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_flowdrawlg
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_flowdrawlg
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    int insert(SaFlowdrawlg row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_flowdrawlg
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    SaFlowdrawlg selectByPrimaryKey(String sid);
    
    /**
     * 根据流程图id获取流程图信息
     * @param sprocessid
     * @return
     */
    SaFlowdrawlg selectByProcessId(String sprocessid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_flowdrawlg
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    List<SaFlowdrawlg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_flowdrawlg
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    int updateByPrimaryKey(SaFlowdrawlg row);
}