package com.tlv8.flw.mapper;

import com.tlv8.flw.pojo.SaFlowdrawlg;
import java.util.List;

public interface SaFlowdrawlgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_flowdrawlg
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_flowdrawlg
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    int insert(SaFlowdrawlg row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_flowdrawlg
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    SaFlowdrawlg selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_flowdrawlg
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    List<SaFlowdrawlg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_flowdrawlg
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    int updateByPrimaryKey(SaFlowdrawlg row);
    
    /**
     * 根据processid获取流程图
     * @param sprocessid
     * @return
     */
    SaFlowdrawlg selectBySprocessid(String sprocessid);
    
    /**
     * 根据页面地址查找流程图
     * @param path
     * @return
     */
    List<SaFlowdrawlg> seachProcessByPath(String path);
    
    /**
     * 根据目录ID查找流程图
     * @param sfolderid
     * @return
     */
    List<SaFlowdrawlg> selectByFolderID(String sfolderid);
}