package com.tlv8.flw.pojo;

import java.io.Serializable;
import java.util.Date;

public class SaFlowdrawlg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.sid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.sprocessid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private String sprocessid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.sprocessname
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private String sprocessname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.sdrawlg
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private String sdrawlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.sprocessacty
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private String sprocessacty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.screatorid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private String screatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.screatorname
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private String screatorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.supdatorid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private String supdatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.supdatorname
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private String supdatorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.screatetime
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private Date screatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.supdatetime
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private Date supdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.fenabled
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private Integer fenabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.sfolderid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private String sfolderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowdrawlg.version
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa_flowdrawlg
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.sid
     *
     * @return the value of sa_flowdrawlg.sid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.sid
     *
     * @param sid the value for sa_flowdrawlg.sid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.sprocessid
     *
     * @return the value of sa_flowdrawlg.sprocessid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public String getSprocessid() {
        return sprocessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.sprocessid
     *
     * @param sprocessid the value for sa_flowdrawlg.sprocessid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setSprocessid(String sprocessid) {
        this.sprocessid = sprocessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.sprocessname
     *
     * @return the value of sa_flowdrawlg.sprocessname
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public String getSprocessname() {
        return sprocessname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.sprocessname
     *
     * @param sprocessname the value for sa_flowdrawlg.sprocessname
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setSprocessname(String sprocessname) {
        this.sprocessname = sprocessname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.sdrawlg
     *
     * @return the value of sa_flowdrawlg.sdrawlg
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public String getSdrawlg() {
        return sdrawlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.sdrawlg
     *
     * @param sdrawlg the value for sa_flowdrawlg.sdrawlg
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setSdrawlg(String sdrawlg) {
        this.sdrawlg = sdrawlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.sprocessacty
     *
     * @return the value of sa_flowdrawlg.sprocessacty
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public String getSprocessacty() {
        return sprocessacty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.sprocessacty
     *
     * @param sprocessacty the value for sa_flowdrawlg.sprocessacty
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setSprocessacty(String sprocessacty) {
        this.sprocessacty = sprocessacty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.screatorid
     *
     * @return the value of sa_flowdrawlg.screatorid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public String getScreatorid() {
        return screatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.screatorid
     *
     * @param screatorid the value for sa_flowdrawlg.screatorid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setScreatorid(String screatorid) {
        this.screatorid = screatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.screatorname
     *
     * @return the value of sa_flowdrawlg.screatorname
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public String getScreatorname() {
        return screatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.screatorname
     *
     * @param screatorname the value for sa_flowdrawlg.screatorname
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setScreatorname(String screatorname) {
        this.screatorname = screatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.supdatorid
     *
     * @return the value of sa_flowdrawlg.supdatorid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public String getSupdatorid() {
        return supdatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.supdatorid
     *
     * @param supdatorid the value for sa_flowdrawlg.supdatorid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setSupdatorid(String supdatorid) {
        this.supdatorid = supdatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.supdatorname
     *
     * @return the value of sa_flowdrawlg.supdatorname
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public String getSupdatorname() {
        return supdatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.supdatorname
     *
     * @param supdatorname the value for sa_flowdrawlg.supdatorname
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setSupdatorname(String supdatorname) {
        this.supdatorname = supdatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.screatetime
     *
     * @return the value of sa_flowdrawlg.screatetime
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public Date getScreatetime() {
        return screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.screatetime
     *
     * @param screatetime the value for sa_flowdrawlg.screatetime
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setScreatetime(Date screatetime) {
        this.screatetime = screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.supdatetime
     *
     * @return the value of sa_flowdrawlg.supdatetime
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public Date getSupdatetime() {
        return supdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.supdatetime
     *
     * @param supdatetime the value for sa_flowdrawlg.supdatetime
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setSupdatetime(Date supdatetime) {
        this.supdatetime = supdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.fenabled
     *
     * @return the value of sa_flowdrawlg.fenabled
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public Integer getFenabled() {
        return fenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.fenabled
     *
     * @param fenabled the value for sa_flowdrawlg.fenabled
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setFenabled(Integer fenabled) {
        this.fenabled = fenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.sfolderid
     *
     * @return the value of sa_flowdrawlg.sfolderid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public String getSfolderid() {
        return sfolderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.sfolderid
     *
     * @param sfolderid the value for sa_flowdrawlg.sfolderid
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setSfolderid(String sfolderid) {
        this.sfolderid = sfolderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowdrawlg.version
     *
     * @return the value of sa_flowdrawlg.version
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowdrawlg.version
     *
     * @param version the value for sa_flowdrawlg.version
     *
     * @mbg.generated Mon Apr 10 20:53:57 CST 2023
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}