package com.tlv8.flw.pojo;

import java.io.Serializable;

public class SaFlowfolder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowfolder.sid
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowfolder.sprocessid
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    private String sprocessid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowfolder.sprocessname
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    private String sprocessname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowfolder.scode
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    private String scode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowfolder.sname
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowfolder.sparent
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    private String sparent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowfolder.sidpath
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    private String sidpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowfolder.snamepath
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    private String snamepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowfolder.scodepath
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    private String scodepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_flowfolder.version
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa_flowfolder
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowfolder.sid
     *
     * @return the value of sa_flowfolder.sid
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowfolder.sid
     *
     * @param sid the value for sa_flowfolder.sid
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowfolder.sprocessid
     *
     * @return the value of sa_flowfolder.sprocessid
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public String getSprocessid() {
        return sprocessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowfolder.sprocessid
     *
     * @param sprocessid the value for sa_flowfolder.sprocessid
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public void setSprocessid(String sprocessid) {
        this.sprocessid = sprocessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowfolder.sprocessname
     *
     * @return the value of sa_flowfolder.sprocessname
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public String getSprocessname() {
        return sprocessname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowfolder.sprocessname
     *
     * @param sprocessname the value for sa_flowfolder.sprocessname
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public void setSprocessname(String sprocessname) {
        this.sprocessname = sprocessname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowfolder.scode
     *
     * @return the value of sa_flowfolder.scode
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowfolder.scode
     *
     * @param scode the value for sa_flowfolder.scode
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public void setScode(String scode) {
        this.scode = scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowfolder.sname
     *
     * @return the value of sa_flowfolder.sname
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowfolder.sname
     *
     * @param sname the value for sa_flowfolder.sname
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowfolder.sparent
     *
     * @return the value of sa_flowfolder.sparent
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public String getSparent() {
        return sparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowfolder.sparent
     *
     * @param sparent the value for sa_flowfolder.sparent
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public void setSparent(String sparent) {
        this.sparent = sparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowfolder.sidpath
     *
     * @return the value of sa_flowfolder.sidpath
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public String getSidpath() {
        return sidpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowfolder.sidpath
     *
     * @param sidpath the value for sa_flowfolder.sidpath
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public void setSidpath(String sidpath) {
        this.sidpath = sidpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowfolder.snamepath
     *
     * @return the value of sa_flowfolder.snamepath
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public String getSnamepath() {
        return snamepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowfolder.snamepath
     *
     * @param snamepath the value for sa_flowfolder.snamepath
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public void setSnamepath(String snamepath) {
        this.snamepath = snamepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowfolder.scodepath
     *
     * @return the value of sa_flowfolder.scodepath
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public String getScodepath() {
        return scodepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowfolder.scodepath
     *
     * @param scodepath the value for sa_flowfolder.scodepath
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public void setScodepath(String scodepath) {
        this.scodepath = scodepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_flowfolder.version
     *
     * @return the value of sa_flowfolder.version
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_flowfolder.version
     *
     * @param version the value for sa_flowfolder.version
     *
     * @mbg.generated Tue Apr 11 10:30:26 CST 2023
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}