package com.tlv8.flw.pojo;

import java.io.Serializable;
import java.util.Date;

import com.tlv8.common.utils.IDUtils;
import com.tlv8.system.bean.ContextBean;

public class SaTask implements Serializable {

	public SaTask() {

	}

	public SaTask(ContextBean context, String sData1) {
		setSid(IDUtils.getGUID());
		setSdata1(sData1);
		setScpersonid(context.getCurrentPersonID());
		setScpersoncode(context.getCurrentPersonCode());
		setScpersonname(context.getCurrentPersonName());
		setScposid(context.getCurrentPositionID());
		setScposcode(context.getCurrentPositionCode());
		setScposname(context.getCurrentPositionName());
		setScdeptid(context.getCurrentDeptID());
		setScdeptcode(context.getCurrentDeptCode());
		setScdeptname(context.getCurrentDeptName());
		setScognid(context.getCurrentOgnID());
		setScogncode(context.getCurrentOgnCode());
		setScognname(context.getCurrentOgnName());
		setScfid(context.getCurrentPersonFullID());
		setScfname(context.getCurrentPersonFullName());
		setScreatetime(new Date());
		setVersion(0);
	}

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sparentid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sparentid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scontent
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scontent;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sremark
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sremark;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sflowid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sflowid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.stypeid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String stypeid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.stypename
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String stypename;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sprocess
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sprocess;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sactivity
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sactivity;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.screatetime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Date screatetime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sdistributetime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Date sdistributetime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.slastmodifytime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Date slastmodifytime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.swarningtime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Date swarningtime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.slimittime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Date slimittime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sestarttime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Date sestarttime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sefinishtime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Date sefinishtime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sastarttime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Date sastarttime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.safinishtime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Date safinishtime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sexecutetime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Date sexecutetime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scpersonid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scpersonid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scpersonname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scpersonname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scdeptid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scdeptid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scdeptname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scdeptname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scognid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scognid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scognname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scognname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sepersonid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sepersonid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sepersonname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sepersonname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sedeptid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sedeptid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sedeptname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sedeptname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.seognid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String seognid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.seognname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String seognname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.slock
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String slock;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sstatusid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sstatusid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sstatusname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sstatusname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.skindid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String skindid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scurl
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scurl;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.seurl
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String seurl;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sexecutemode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sexecutemode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.ssequence
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Integer ssequence;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scpersoncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scpersoncode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scposid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scposid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scposcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scposcode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scposname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scposname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scdeptcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scdeptcode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scogncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scogncode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scfid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scfid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sepersoncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sepersoncode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.seposid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String seposid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.seposcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String seposcode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.seposname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String seposname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sedeptcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sedeptcode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.seogncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String seogncode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sefid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sefid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sdata1
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sdata1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sdata2
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sdata2;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sdata3
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sdata3;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sdata4
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sdata4;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.scfname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String scfname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.sefname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private String sefname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sa_task.version
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private Integer version;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table sa_task
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sid
	 *
	 * @return the value of sa_task.sid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sid
	 *
	 * @param sid the value for sa_task.sid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSid(String sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sparentid
	 *
	 * @return the value of sa_task.sparentid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSparentid() {
		return sparentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sparentid
	 *
	 * @param sparentid the value for sa_task.sparentid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSparentid(String sparentid) {
		this.sparentid = sparentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sname
	 *
	 * @return the value of sa_task.sname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSname() {
		return sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sname
	 *
	 * @param sname the value for sa_task.sname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSname(String sname) {
		this.sname = sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scontent
	 *
	 * @return the value of sa_task.scontent
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScontent() {
		return scontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scontent
	 *
	 * @param scontent the value for sa_task.scontent
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScontent(String scontent) {
		this.scontent = scontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sremark
	 *
	 * @return the value of sa_task.sremark
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSremark() {
		return sremark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sremark
	 *
	 * @param sremark the value for sa_task.sremark
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSremark(String sremark) {
		this.sremark = sremark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sflowid
	 *
	 * @return the value of sa_task.sflowid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSflowid() {
		return sflowid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sflowid
	 *
	 * @param sflowid the value for sa_task.sflowid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSflowid(String sflowid) {
		this.sflowid = sflowid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.stypeid
	 *
	 * @return the value of sa_task.stypeid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getStypeid() {
		return stypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.stypeid
	 *
	 * @param stypeid the value for sa_task.stypeid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setStypeid(String stypeid) {
		this.stypeid = stypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.stypename
	 *
	 * @return the value of sa_task.stypename
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getStypename() {
		return stypename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.stypename
	 *
	 * @param stypename the value for sa_task.stypename
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setStypename(String stypename) {
		this.stypename = stypename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sprocess
	 *
	 * @return the value of sa_task.sprocess
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSprocess() {
		return sprocess;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sprocess
	 *
	 * @param sprocess the value for sa_task.sprocess
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSprocess(String sprocess) {
		this.sprocess = sprocess;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sactivity
	 *
	 * @return the value of sa_task.sactivity
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSactivity() {
		return sactivity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sactivity
	 *
	 * @param sactivity the value for sa_task.sactivity
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSactivity(String sactivity) {
		this.sactivity = sactivity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.screatetime
	 *
	 * @return the value of sa_task.screatetime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Date getScreatetime() {
		return screatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.screatetime
	 *
	 * @param screatetime the value for sa_task.screatetime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScreatetime(Date screatetime) {
		this.screatetime = screatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sdistributetime
	 *
	 * @return the value of sa_task.sdistributetime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Date getSdistributetime() {
		return sdistributetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sdistributetime
	 *
	 * @param sdistributetime the value for sa_task.sdistributetime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSdistributetime(Date sdistributetime) {
		this.sdistributetime = sdistributetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.slastmodifytime
	 *
	 * @return the value of sa_task.slastmodifytime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Date getSlastmodifytime() {
		return slastmodifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.slastmodifytime
	 *
	 * @param slastmodifytime the value for sa_task.slastmodifytime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSlastmodifytime(Date slastmodifytime) {
		this.slastmodifytime = slastmodifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.swarningtime
	 *
	 * @return the value of sa_task.swarningtime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Date getSwarningtime() {
		return swarningtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.swarningtime
	 *
	 * @param swarningtime the value for sa_task.swarningtime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSwarningtime(Date swarningtime) {
		this.swarningtime = swarningtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.slimittime
	 *
	 * @return the value of sa_task.slimittime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Date getSlimittime() {
		return slimittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.slimittime
	 *
	 * @param slimittime the value for sa_task.slimittime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSlimittime(Date slimittime) {
		this.slimittime = slimittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sestarttime
	 *
	 * @return the value of sa_task.sestarttime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Date getSestarttime() {
		return sestarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sestarttime
	 *
	 * @param sestarttime the value for sa_task.sestarttime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSestarttime(Date sestarttime) {
		this.sestarttime = sestarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sefinishtime
	 *
	 * @return the value of sa_task.sefinishtime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Date getSefinishtime() {
		return sefinishtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sefinishtime
	 *
	 * @param sefinishtime the value for sa_task.sefinishtime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSefinishtime(Date sefinishtime) {
		this.sefinishtime = sefinishtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sastarttime
	 *
	 * @return the value of sa_task.sastarttime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Date getSastarttime() {
		return sastarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sastarttime
	 *
	 * @param sastarttime the value for sa_task.sastarttime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSastarttime(Date sastarttime) {
		this.sastarttime = sastarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.safinishtime
	 *
	 * @return the value of sa_task.safinishtime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Date getSafinishtime() {
		return safinishtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.safinishtime
	 *
	 * @param safinishtime the value for sa_task.safinishtime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSafinishtime(Date safinishtime) {
		this.safinishtime = safinishtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sexecutetime
	 *
	 * @return the value of sa_task.sexecutetime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Date getSexecutetime() {
		return sexecutetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sexecutetime
	 *
	 * @param sexecutetime the value for sa_task.sexecutetime
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSexecutetime(Date sexecutetime) {
		this.sexecutetime = sexecutetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scpersonid
	 *
	 * @return the value of sa_task.scpersonid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScpersonid() {
		return scpersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scpersonid
	 *
	 * @param scpersonid the value for sa_task.scpersonid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScpersonid(String scpersonid) {
		this.scpersonid = scpersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scpersonname
	 *
	 * @return the value of sa_task.scpersonname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScpersonname() {
		return scpersonname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scpersonname
	 *
	 * @param scpersonname the value for sa_task.scpersonname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScpersonname(String scpersonname) {
		this.scpersonname = scpersonname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scdeptid
	 *
	 * @return the value of sa_task.scdeptid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScdeptid() {
		return scdeptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scdeptid
	 *
	 * @param scdeptid the value for sa_task.scdeptid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScdeptid(String scdeptid) {
		this.scdeptid = scdeptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scdeptname
	 *
	 * @return the value of sa_task.scdeptname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScdeptname() {
		return scdeptname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scdeptname
	 *
	 * @param scdeptname the value for sa_task.scdeptname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScdeptname(String scdeptname) {
		this.scdeptname = scdeptname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scognid
	 *
	 * @return the value of sa_task.scognid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScognid() {
		return scognid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scognid
	 *
	 * @param scognid the value for sa_task.scognid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScognid(String scognid) {
		this.scognid = scognid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scognname
	 *
	 * @return the value of sa_task.scognname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScognname() {
		return scognname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scognname
	 *
	 * @param scognname the value for sa_task.scognname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScognname(String scognname) {
		this.scognname = scognname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sepersonid
	 *
	 * @return the value of sa_task.sepersonid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSepersonid() {
		return sepersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sepersonid
	 *
	 * @param sepersonid the value for sa_task.sepersonid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSepersonid(String sepersonid) {
		this.sepersonid = sepersonid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sepersonname
	 *
	 * @return the value of sa_task.sepersonname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSepersonname() {
		return sepersonname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sepersonname
	 *
	 * @param sepersonname the value for sa_task.sepersonname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSepersonname(String sepersonname) {
		this.sepersonname = sepersonname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sedeptid
	 *
	 * @return the value of sa_task.sedeptid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSedeptid() {
		return sedeptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sedeptid
	 *
	 * @param sedeptid the value for sa_task.sedeptid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSedeptid(String sedeptid) {
		this.sedeptid = sedeptid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sedeptname
	 *
	 * @return the value of sa_task.sedeptname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSedeptname() {
		return sedeptname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sedeptname
	 *
	 * @param sedeptname the value for sa_task.sedeptname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSedeptname(String sedeptname) {
		this.sedeptname = sedeptname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.seognid
	 *
	 * @return the value of sa_task.seognid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSeognid() {
		return seognid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.seognid
	 *
	 * @param seognid the value for sa_task.seognid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSeognid(String seognid) {
		this.seognid = seognid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.seognname
	 *
	 * @return the value of sa_task.seognname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSeognname() {
		return seognname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.seognname
	 *
	 * @param seognname the value for sa_task.seognname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSeognname(String seognname) {
		this.seognname = seognname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.slock
	 *
	 * @return the value of sa_task.slock
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSlock() {
		return slock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.slock
	 *
	 * @param slock the value for sa_task.slock
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSlock(String slock) {
		this.slock = slock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sstatusid
	 *
	 * @return the value of sa_task.sstatusid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSstatusid() {
		return sstatusid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sstatusid
	 *
	 * @param sstatusid the value for sa_task.sstatusid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSstatusid(String sstatusid) {
		this.sstatusid = sstatusid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sstatusname
	 *
	 * @return the value of sa_task.sstatusname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSstatusname() {
		return sstatusname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sstatusname
	 *
	 * @param sstatusname the value for sa_task.sstatusname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSstatusname(String sstatusname) {
		this.sstatusname = sstatusname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.skindid
	 *
	 * @return the value of sa_task.skindid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSkindid() {
		return skindid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.skindid
	 *
	 * @param skindid the value for sa_task.skindid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSkindid(String skindid) {
		this.skindid = skindid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scurl
	 *
	 * @return the value of sa_task.scurl
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScurl() {
		return scurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scurl
	 *
	 * @param scurl the value for sa_task.scurl
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScurl(String scurl) {
		this.scurl = scurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.seurl
	 *
	 * @return the value of sa_task.seurl
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSeurl() {
		return seurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.seurl
	 *
	 * @param seurl the value for sa_task.seurl
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSeurl(String seurl) {
		this.seurl = seurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sexecutemode
	 *
	 * @return the value of sa_task.sexecutemode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSexecutemode() {
		return sexecutemode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sexecutemode
	 *
	 * @param sexecutemode the value for sa_task.sexecutemode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSexecutemode(String sexecutemode) {
		this.sexecutemode = sexecutemode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.ssequence
	 *
	 * @return the value of sa_task.ssequence
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Integer getSsequence() {
		return ssequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.ssequence
	 *
	 * @param ssequence the value for sa_task.ssequence
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSsequence(Integer ssequence) {
		this.ssequence = ssequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scpersoncode
	 *
	 * @return the value of sa_task.scpersoncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScpersoncode() {
		return scpersoncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scpersoncode
	 *
	 * @param scpersoncode the value for sa_task.scpersoncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScpersoncode(String scpersoncode) {
		this.scpersoncode = scpersoncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scposid
	 *
	 * @return the value of sa_task.scposid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScposid() {
		return scposid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scposid
	 *
	 * @param scposid the value for sa_task.scposid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScposid(String scposid) {
		this.scposid = scposid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scposcode
	 *
	 * @return the value of sa_task.scposcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScposcode() {
		return scposcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scposcode
	 *
	 * @param scposcode the value for sa_task.scposcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScposcode(String scposcode) {
		this.scposcode = scposcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scposname
	 *
	 * @return the value of sa_task.scposname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScposname() {
		return scposname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scposname
	 *
	 * @param scposname the value for sa_task.scposname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScposname(String scposname) {
		this.scposname = scposname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scdeptcode
	 *
	 * @return the value of sa_task.scdeptcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScdeptcode() {
		return scdeptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scdeptcode
	 *
	 * @param scdeptcode the value for sa_task.scdeptcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScdeptcode(String scdeptcode) {
		this.scdeptcode = scdeptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scogncode
	 *
	 * @return the value of sa_task.scogncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScogncode() {
		return scogncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scogncode
	 *
	 * @param scogncode the value for sa_task.scogncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScogncode(String scogncode) {
		this.scogncode = scogncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scfid
	 *
	 * @return the value of sa_task.scfid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScfid() {
		return scfid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scfid
	 *
	 * @param scfid the value for sa_task.scfid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScfid(String scfid) {
		this.scfid = scfid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sepersoncode
	 *
	 * @return the value of sa_task.sepersoncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSepersoncode() {
		return sepersoncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sepersoncode
	 *
	 * @param sepersoncode the value for sa_task.sepersoncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSepersoncode(String sepersoncode) {
		this.sepersoncode = sepersoncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.seposid
	 *
	 * @return the value of sa_task.seposid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSeposid() {
		return seposid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.seposid
	 *
	 * @param seposid the value for sa_task.seposid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSeposid(String seposid) {
		this.seposid = seposid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.seposcode
	 *
	 * @return the value of sa_task.seposcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSeposcode() {
		return seposcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.seposcode
	 *
	 * @param seposcode the value for sa_task.seposcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSeposcode(String seposcode) {
		this.seposcode = seposcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.seposname
	 *
	 * @return the value of sa_task.seposname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSeposname() {
		return seposname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.seposname
	 *
	 * @param seposname the value for sa_task.seposname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSeposname(String seposname) {
		this.seposname = seposname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sedeptcode
	 *
	 * @return the value of sa_task.sedeptcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSedeptcode() {
		return sedeptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sedeptcode
	 *
	 * @param sedeptcode the value for sa_task.sedeptcode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSedeptcode(String sedeptcode) {
		this.sedeptcode = sedeptcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.seogncode
	 *
	 * @return the value of sa_task.seogncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSeogncode() {
		return seogncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.seogncode
	 *
	 * @param seogncode the value for sa_task.seogncode
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSeogncode(String seogncode) {
		this.seogncode = seogncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sefid
	 *
	 * @return the value of sa_task.sefid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSefid() {
		return sefid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sefid
	 *
	 * @param sefid the value for sa_task.sefid
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSefid(String sefid) {
		this.sefid = sefid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sdata1
	 *
	 * @return the value of sa_task.sdata1
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSdata1() {
		return sdata1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sdata1
	 *
	 * @param sdata1 the value for sa_task.sdata1
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSdata1(String sdata1) {
		this.sdata1 = sdata1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sdata2
	 *
	 * @return the value of sa_task.sdata2
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSdata2() {
		return sdata2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sdata2
	 *
	 * @param sdata2 the value for sa_task.sdata2
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSdata2(String sdata2) {
		this.sdata2 = sdata2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sdata3
	 *
	 * @return the value of sa_task.sdata3
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSdata3() {
		return sdata3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sdata3
	 *
	 * @param sdata3 the value for sa_task.sdata3
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSdata3(String sdata3) {
		this.sdata3 = sdata3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sdata4
	 *
	 * @return the value of sa_task.sdata4
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSdata4() {
		return sdata4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sdata4
	 *
	 * @param sdata4 the value for sa_task.sdata4
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSdata4(String sdata4) {
		this.sdata4 = sdata4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.scfname
	 *
	 * @return the value of sa_task.scfname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getScfname() {
		return scfname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.scfname
	 *
	 * @param scfname the value for sa_task.scfname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setScfname(String scfname) {
		this.scfname = scfname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.sefname
	 *
	 * @return the value of sa_task.sefname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public String getSefname() {
		return sefname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.sefname
	 *
	 * @param sefname the value for sa_task.sefname
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setSefname(String sefname) {
		this.sefname = sefname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sa_task.version
	 *
	 * @return the value of sa_task.version
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sa_task.version
	 *
	 * @param version the value for sa_task.version
	 *
	 * @mbg.generated Thu Apr 13 10:37:34 CST 2023
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}
}