package com.tlv8.oa.pojo;

import java.io.Serializable;
import java.util.Date;

public class BoEntry implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.fid
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.title
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.content
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.category_id
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.category_name
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.comment_hit
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private Integer commentHit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.allow_comment
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private Integer allowComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.status
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.created_time
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.updated_time
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.hits
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private Integer hits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.bo_blogid
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private String boBlogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.accessories
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private String accessories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.fextend01
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private String fextend01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.oneself
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private String oneself;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.creatorid
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private String creatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bo_entry.version
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bo_entry
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.fid
     *
     * @return the value of bo_entry.fid
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.fid
     *
     * @param fid the value for bo_entry.fid
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.title
     *
     * @return the value of bo_entry.title
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.title
     *
     * @param title the value for bo_entry.title
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.content
     *
     * @return the value of bo_entry.content
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.content
     *
     * @param content the value for bo_entry.content
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.category_id
     *
     * @return the value of bo_entry.category_id
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.category_id
     *
     * @param categoryId the value for bo_entry.category_id
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.category_name
     *
     * @return the value of bo_entry.category_name
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.category_name
     *
     * @param categoryName the value for bo_entry.category_name
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.comment_hit
     *
     * @return the value of bo_entry.comment_hit
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public Integer getCommentHit() {
        return commentHit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.comment_hit
     *
     * @param commentHit the value for bo_entry.comment_hit
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setCommentHit(Integer commentHit) {
        this.commentHit = commentHit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.allow_comment
     *
     * @return the value of bo_entry.allow_comment
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public Integer getAllowComment() {
        return allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.allow_comment
     *
     * @param allowComment the value for bo_entry.allow_comment
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setAllowComment(Integer allowComment) {
        this.allowComment = allowComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.status
     *
     * @return the value of bo_entry.status
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.status
     *
     * @param status the value for bo_entry.status
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.created_time
     *
     * @return the value of bo_entry.created_time
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.created_time
     *
     * @param createdTime the value for bo_entry.created_time
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.updated_time
     *
     * @return the value of bo_entry.updated_time
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.updated_time
     *
     * @param updatedTime the value for bo_entry.updated_time
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.hits
     *
     * @return the value of bo_entry.hits
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public Integer getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.hits
     *
     * @param hits the value for bo_entry.hits
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setHits(Integer hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.bo_blogid
     *
     * @return the value of bo_entry.bo_blogid
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public String getBoBlogid() {
        return boBlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.bo_blogid
     *
     * @param boBlogid the value for bo_entry.bo_blogid
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setBoBlogid(String boBlogid) {
        this.boBlogid = boBlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.accessories
     *
     * @return the value of bo_entry.accessories
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public String getAccessories() {
        return accessories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.accessories
     *
     * @param accessories the value for bo_entry.accessories
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setAccessories(String accessories) {
        this.accessories = accessories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.fextend01
     *
     * @return the value of bo_entry.fextend01
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public String getFextend01() {
        return fextend01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.fextend01
     *
     * @param fextend01 the value for bo_entry.fextend01
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setFextend01(String fextend01) {
        this.fextend01 = fextend01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.oneself
     *
     * @return the value of bo_entry.oneself
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public String getOneself() {
        return oneself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.oneself
     *
     * @param oneself the value for bo_entry.oneself
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setOneself(String oneself) {
        this.oneself = oneself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.creatorid
     *
     * @return the value of bo_entry.creatorid
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.creatorid
     *
     * @param creatorid the value for bo_entry.creatorid
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bo_entry.version
     *
     * @return the value of bo_entry.version
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bo_entry.version
     *
     * @param version the value for bo_entry.version
     *
     * @mbg.generated Thu Mar 21 13:52:33 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}