package com.tlv8.oa.pojo;

import java.io.Serializable;
import java.util.Date;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

@TableName("OA_EM_SendEmail")
public class OaEmSendemail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
	@TableId
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.femailname
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String femailname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fconsignee
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String fconsignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.ftext
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String ftext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fstate
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String fstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fconsigneeid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String fconsigneeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fconsigneecode
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String fconsigneecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.ffjid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String ffjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fsendpername
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String fsendpername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fsendperid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String fsendperid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fcreattime
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private Date fcreattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fsendtime
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private Date fsendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fsendpercode
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String fsendpercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fsendogn
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String fsendogn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fsenddept
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String fsenddept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.fcollect
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private String fcollect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_em_sendemail.version
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_em_sendemail
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fid
     *
     * @return the value of oa_em_sendemail.fid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fid
     *
     * @param fid the value for oa_em_sendemail.fid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.femailname
     *
     * @return the value of oa_em_sendemail.femailname
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFemailname() {
        return femailname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.femailname
     *
     * @param femailname the value for oa_em_sendemail.femailname
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFemailname(String femailname) {
        this.femailname = femailname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fconsignee
     *
     * @return the value of oa_em_sendemail.fconsignee
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFconsignee() {
        return fconsignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fconsignee
     *
     * @param fconsignee the value for oa_em_sendemail.fconsignee
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFconsignee(String fconsignee) {
        this.fconsignee = fconsignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.ftext
     *
     * @return the value of oa_em_sendemail.ftext
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFtext() {
        return ftext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.ftext
     *
     * @param ftext the value for oa_em_sendemail.ftext
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFtext(String ftext) {
        this.ftext = ftext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fstate
     *
     * @return the value of oa_em_sendemail.fstate
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFstate() {
        return fstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fstate
     *
     * @param fstate the value for oa_em_sendemail.fstate
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFstate(String fstate) {
        this.fstate = fstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fconsigneeid
     *
     * @return the value of oa_em_sendemail.fconsigneeid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFconsigneeid() {
        return fconsigneeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fconsigneeid
     *
     * @param fconsigneeid the value for oa_em_sendemail.fconsigneeid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFconsigneeid(String fconsigneeid) {
        this.fconsigneeid = fconsigneeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fconsigneecode
     *
     * @return the value of oa_em_sendemail.fconsigneecode
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFconsigneecode() {
        return fconsigneecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fconsigneecode
     *
     * @param fconsigneecode the value for oa_em_sendemail.fconsigneecode
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFconsigneecode(String fconsigneecode) {
        this.fconsigneecode = fconsigneecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.ffjid
     *
     * @return the value of oa_em_sendemail.ffjid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFfjid() {
        return ffjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.ffjid
     *
     * @param ffjid the value for oa_em_sendemail.ffjid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFfjid(String ffjid) {
        this.ffjid = ffjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fsendpername
     *
     * @return the value of oa_em_sendemail.fsendpername
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFsendpername() {
        return fsendpername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fsendpername
     *
     * @param fsendpername the value for oa_em_sendemail.fsendpername
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFsendpername(String fsendpername) {
        this.fsendpername = fsendpername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fsendperid
     *
     * @return the value of oa_em_sendemail.fsendperid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFsendperid() {
        return fsendperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fsendperid
     *
     * @param fsendperid the value for oa_em_sendemail.fsendperid
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFsendperid(String fsendperid) {
        this.fsendperid = fsendperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fcreattime
     *
     * @return the value of oa_em_sendemail.fcreattime
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public Date getFcreattime() {
        return fcreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fcreattime
     *
     * @param fcreattime the value for oa_em_sendemail.fcreattime
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFcreattime(Date fcreattime) {
        this.fcreattime = fcreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fsendtime
     *
     * @return the value of oa_em_sendemail.fsendtime
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public Date getFsendtime() {
        return fsendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fsendtime
     *
     * @param fsendtime the value for oa_em_sendemail.fsendtime
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFsendtime(Date fsendtime) {
        this.fsendtime = fsendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fsendpercode
     *
     * @return the value of oa_em_sendemail.fsendpercode
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFsendpercode() {
        return fsendpercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fsendpercode
     *
     * @param fsendpercode the value for oa_em_sendemail.fsendpercode
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFsendpercode(String fsendpercode) {
        this.fsendpercode = fsendpercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fsendogn
     *
     * @return the value of oa_em_sendemail.fsendogn
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFsendogn() {
        return fsendogn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fsendogn
     *
     * @param fsendogn the value for oa_em_sendemail.fsendogn
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFsendogn(String fsendogn) {
        this.fsendogn = fsendogn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fsenddept
     *
     * @return the value of oa_em_sendemail.fsenddept
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFsenddept() {
        return fsenddept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fsenddept
     *
     * @param fsenddept the value for oa_em_sendemail.fsenddept
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFsenddept(String fsenddept) {
        this.fsenddept = fsenddept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.fcollect
     *
     * @return the value of oa_em_sendemail.fcollect
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public String getFcollect() {
        return fcollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.fcollect
     *
     * @param fcollect the value for oa_em_sendemail.fcollect
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setFcollect(String fcollect) {
        this.fcollect = fcollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_em_sendemail.version
     *
     * @return the value of oa_em_sendemail.version
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_em_sendemail.version
     *
     * @param version the value for oa_em_sendemail.version
     *
     * @mbg.generated Wed Mar 20 10:48:47 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}