package com.tlv8.oa.pojo;

import java.io.Serializable;
import java.util.Date;

public class OaNewsCount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_count.fid
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_count.news_releaseid
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    private String newsReleaseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_count.yetperson
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    private String yetperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_count.yetpersonid
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    private String yetpersonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_count.yetdate
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    private Date yetdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_count.version
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_news_count
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_count.fid
     *
     * @return the value of oa_news_count.fid
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_count.fid
     *
     * @param fid the value for oa_news_count.fid
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_count.news_releaseid
     *
     * @return the value of oa_news_count.news_releaseid
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public String getNewsReleaseid() {
        return newsReleaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_count.news_releaseid
     *
     * @param newsReleaseid the value for oa_news_count.news_releaseid
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public void setNewsReleaseid(String newsReleaseid) {
        this.newsReleaseid = newsReleaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_count.yetperson
     *
     * @return the value of oa_news_count.yetperson
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public String getYetperson() {
        return yetperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_count.yetperson
     *
     * @param yetperson the value for oa_news_count.yetperson
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public void setYetperson(String yetperson) {
        this.yetperson = yetperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_count.yetpersonid
     *
     * @return the value of oa_news_count.yetpersonid
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public String getYetpersonid() {
        return yetpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_count.yetpersonid
     *
     * @param yetpersonid the value for oa_news_count.yetpersonid
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public void setYetpersonid(String yetpersonid) {
        this.yetpersonid = yetpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_count.yetdate
     *
     * @return the value of oa_news_count.yetdate
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public Date getYetdate() {
        return yetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_count.yetdate
     *
     * @param yetdate the value for oa_news_count.yetdate
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public void setYetdate(Date yetdate) {
        this.yetdate = yetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_count.version
     *
     * @return the value of oa_news_count.version
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_count.version
     *
     * @param version the value for oa_news_count.version
     *
     * @mbg.generated Thu Mar 21 16:06:36 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}