package com.tlv8.oa.pojo;

import java.io.Serializable;

public class OaNewsColumn implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_column.fid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_column.fcolumncode
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private String fcolumncode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_column.fcolumnname
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private String fcolumnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_column.fcolumndescribes
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private String fcolumndescribes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_column.fcolumnstate
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private String fcolumnstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_column.version
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_news_column
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_column.fid
     *
     * @return the value of oa_news_column.fid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_column.fid
     *
     * @param fid the value for oa_news_column.fid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_column.fcolumncode
     *
     * @return the value of oa_news_column.fcolumncode
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public String getFcolumncode() {
        return fcolumncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_column.fcolumncode
     *
     * @param fcolumncode the value for oa_news_column.fcolumncode
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public void setFcolumncode(String fcolumncode) {
        this.fcolumncode = fcolumncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_column.fcolumnname
     *
     * @return the value of oa_news_column.fcolumnname
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public String getFcolumnname() {
        return fcolumnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_column.fcolumnname
     *
     * @param fcolumnname the value for oa_news_column.fcolumnname
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public void setFcolumnname(String fcolumnname) {
        this.fcolumnname = fcolumnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_column.fcolumndescribes
     *
     * @return the value of oa_news_column.fcolumndescribes
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public String getFcolumndescribes() {
        return fcolumndescribes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_column.fcolumndescribes
     *
     * @param fcolumndescribes the value for oa_news_column.fcolumndescribes
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public void setFcolumndescribes(String fcolumndescribes) {
        this.fcolumndescribes = fcolumndescribes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_column.fcolumnstate
     *
     * @return the value of oa_news_column.fcolumnstate
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public String getFcolumnstate() {
        return fcolumnstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_column.fcolumnstate
     *
     * @param fcolumnstate the value for oa_news_column.fcolumnstate
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public void setFcolumnstate(String fcolumnstate) {
        this.fcolumnstate = fcolumnstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_column.version
     *
     * @return the value of oa_news_column.version
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_column.version
     *
     * @param version the value for oa_news_column.version
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}