package com.tlv8.oa.pojo;

import java.io.Serializable;
import java.util.Date;

public class OaNewsRelease implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.fid
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.fnewstitle
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private String fnewstitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.freleasedepartment
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private String freleasedepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.fpeople
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private String fpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.ftime
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private Date ftime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.fnewsnumber
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private String fnewsnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.freleaseconnext
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private String freleaseconnext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.fstate
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private String fstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.fsettopwhether
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private String fsettopwhether;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.fsettoptime
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private Date fsettoptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.fsetendtime
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private Date fsetendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.faccessories
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private String faccessories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.fcolumnname
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private String fcolumnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.ftype
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private String ftype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.version
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_release.sminipic
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private byte[] sminipic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_news_release
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.fid
     *
     * @return the value of oa_news_release.fid
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.fid
     *
     * @param fid the value for oa_news_release.fid
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.fnewstitle
     *
     * @return the value of oa_news_release.fnewstitle
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public String getFnewstitle() {
        return fnewstitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.fnewstitle
     *
     * @param fnewstitle the value for oa_news_release.fnewstitle
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFnewstitle(String fnewstitle) {
        this.fnewstitle = fnewstitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.freleasedepartment
     *
     * @return the value of oa_news_release.freleasedepartment
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public String getFreleasedepartment() {
        return freleasedepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.freleasedepartment
     *
     * @param freleasedepartment the value for oa_news_release.freleasedepartment
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFreleasedepartment(String freleasedepartment) {
        this.freleasedepartment = freleasedepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.fpeople
     *
     * @return the value of oa_news_release.fpeople
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public String getFpeople() {
        return fpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.fpeople
     *
     * @param fpeople the value for oa_news_release.fpeople
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFpeople(String fpeople) {
        this.fpeople = fpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.ftime
     *
     * @return the value of oa_news_release.ftime
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public Date getFtime() {
        return ftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.ftime
     *
     * @param ftime the value for oa_news_release.ftime
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFtime(Date ftime) {
        this.ftime = ftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.fnewsnumber
     *
     * @return the value of oa_news_release.fnewsnumber
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public String getFnewsnumber() {
        return fnewsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.fnewsnumber
     *
     * @param fnewsnumber the value for oa_news_release.fnewsnumber
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFnewsnumber(String fnewsnumber) {
        this.fnewsnumber = fnewsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.freleaseconnext
     *
     * @return the value of oa_news_release.freleaseconnext
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public String getFreleaseconnext() {
        return freleaseconnext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.freleaseconnext
     *
     * @param freleaseconnext the value for oa_news_release.freleaseconnext
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFreleaseconnext(String freleaseconnext) {
        this.freleaseconnext = freleaseconnext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.fstate
     *
     * @return the value of oa_news_release.fstate
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public String getFstate() {
        return fstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.fstate
     *
     * @param fstate the value for oa_news_release.fstate
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFstate(String fstate) {
        this.fstate = fstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.fsettopwhether
     *
     * @return the value of oa_news_release.fsettopwhether
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public String getFsettopwhether() {
        return fsettopwhether;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.fsettopwhether
     *
     * @param fsettopwhether the value for oa_news_release.fsettopwhether
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFsettopwhether(String fsettopwhether) {
        this.fsettopwhether = fsettopwhether;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.fsettoptime
     *
     * @return the value of oa_news_release.fsettoptime
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public Date getFsettoptime() {
        return fsettoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.fsettoptime
     *
     * @param fsettoptime the value for oa_news_release.fsettoptime
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFsettoptime(Date fsettoptime) {
        this.fsettoptime = fsettoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.fsetendtime
     *
     * @return the value of oa_news_release.fsetendtime
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public Date getFsetendtime() {
        return fsetendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.fsetendtime
     *
     * @param fsetendtime the value for oa_news_release.fsetendtime
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFsetendtime(Date fsetendtime) {
        this.fsetendtime = fsetendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.faccessories
     *
     * @return the value of oa_news_release.faccessories
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public String getFaccessories() {
        return faccessories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.faccessories
     *
     * @param faccessories the value for oa_news_release.faccessories
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFaccessories(String faccessories) {
        this.faccessories = faccessories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.fcolumnname
     *
     * @return the value of oa_news_release.fcolumnname
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public String getFcolumnname() {
        return fcolumnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.fcolumnname
     *
     * @param fcolumnname the value for oa_news_release.fcolumnname
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFcolumnname(String fcolumnname) {
        this.fcolumnname = fcolumnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.ftype
     *
     * @return the value of oa_news_release.ftype
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.ftype
     *
     * @param ftype the value for oa_news_release.ftype
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setFtype(String ftype) {
        this.ftype = ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.version
     *
     * @return the value of oa_news_release.version
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.version
     *
     * @param version the value for oa_news_release.version
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_release.sminipic
     *
     * @return the value of oa_news_release.sminipic
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public byte[] getSminipic() {
        return sminipic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_release.sminipic
     *
     * @param sminipic the value for oa_news_release.sminipic
     *
     * @mbg.generated Thu Mar 21 16:14:53 CST 2024
     */
    public void setSminipic(byte[] sminipic) {
        this.sminipic = sminipic;
    }
}