package com.tlv8.oa.pojo;

import java.io.Serializable;

public class OaNewsOpen implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_open.fid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_open.fopenid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private String fopenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_open.fopenname
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private String fopenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_open.fnewsid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private String fnewsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_news_open.version
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_news_open
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_open.fid
     *
     * @return the value of oa_news_open.fid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_open.fid
     *
     * @param fid the value for oa_news_open.fid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_open.fopenid
     *
     * @return the value of oa_news_open.fopenid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public String getFopenid() {
        return fopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_open.fopenid
     *
     * @param fopenid the value for oa_news_open.fopenid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public void setFopenid(String fopenid) {
        this.fopenid = fopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_open.fopenname
     *
     * @return the value of oa_news_open.fopenname
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public String getFopenname() {
        return fopenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_open.fopenname
     *
     * @param fopenname the value for oa_news_open.fopenname
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public void setFopenname(String fopenname) {
        this.fopenname = fopenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_open.fnewsid
     *
     * @return the value of oa_news_open.fnewsid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public String getFnewsid() {
        return fnewsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_open.fnewsid
     *
     * @param fnewsid the value for oa_news_open.fnewsid
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public void setFnewsid(String fnewsid) {
        this.fnewsid = fnewsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_news_open.version
     *
     * @return the value of oa_news_open.version
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_news_open.version
     *
     * @param version the value for oa_news_open.version
     *
     * @mbg.generated Thu Mar 21 14:38:23 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}