package com.tlv8.oa.pojo;

import java.io.Serializable;
import java.util.Date;

public class OaNoticePerson implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fognid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fognid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fognname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fognname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.forgid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String forgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.forgname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String forgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fcreateid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fcreateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fcreatename
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fcreatename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fcreatedatetime
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private Date fcreatedatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fpersonid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fpersonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fpersonname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fpersonname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.freaddate
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private Date freaddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fpersonfname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fpersonfname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fmainid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fmainid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fbrowse
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fbrowse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fdeptname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fdeptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.fdeptid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private String fdeptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_notice_person.version
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_notice_person
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fid
     *
     * @return the value of oa_notice_person.fid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fid
     *
     * @param fid the value for oa_notice_person.fid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fognid
     *
     * @return the value of oa_notice_person.fognid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFognid() {
        return fognid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fognid
     *
     * @param fognid the value for oa_notice_person.fognid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFognid(String fognid) {
        this.fognid = fognid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fognname
     *
     * @return the value of oa_notice_person.fognname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFognname() {
        return fognname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fognname
     *
     * @param fognname the value for oa_notice_person.fognname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFognname(String fognname) {
        this.fognname = fognname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.forgid
     *
     * @return the value of oa_notice_person.forgid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getForgid() {
        return forgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.forgid
     *
     * @param forgid the value for oa_notice_person.forgid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setForgid(String forgid) {
        this.forgid = forgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.forgname
     *
     * @return the value of oa_notice_person.forgname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getForgname() {
        return forgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.forgname
     *
     * @param forgname the value for oa_notice_person.forgname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setForgname(String forgname) {
        this.forgname = forgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fcreateid
     *
     * @return the value of oa_notice_person.fcreateid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFcreateid() {
        return fcreateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fcreateid
     *
     * @param fcreateid the value for oa_notice_person.fcreateid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFcreateid(String fcreateid) {
        this.fcreateid = fcreateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fcreatename
     *
     * @return the value of oa_notice_person.fcreatename
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFcreatename() {
        return fcreatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fcreatename
     *
     * @param fcreatename the value for oa_notice_person.fcreatename
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFcreatename(String fcreatename) {
        this.fcreatename = fcreatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fcreatedatetime
     *
     * @return the value of oa_notice_person.fcreatedatetime
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public Date getFcreatedatetime() {
        return fcreatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fcreatedatetime
     *
     * @param fcreatedatetime the value for oa_notice_person.fcreatedatetime
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFcreatedatetime(Date fcreatedatetime) {
        this.fcreatedatetime = fcreatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fpersonid
     *
     * @return the value of oa_notice_person.fpersonid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFpersonid() {
        return fpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fpersonid
     *
     * @param fpersonid the value for oa_notice_person.fpersonid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFpersonid(String fpersonid) {
        this.fpersonid = fpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fpersonname
     *
     * @return the value of oa_notice_person.fpersonname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFpersonname() {
        return fpersonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fpersonname
     *
     * @param fpersonname the value for oa_notice_person.fpersonname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFpersonname(String fpersonname) {
        this.fpersonname = fpersonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.freaddate
     *
     * @return the value of oa_notice_person.freaddate
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public Date getFreaddate() {
        return freaddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.freaddate
     *
     * @param freaddate the value for oa_notice_person.freaddate
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFreaddate(Date freaddate) {
        this.freaddate = freaddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fpersonfname
     *
     * @return the value of oa_notice_person.fpersonfname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFpersonfname() {
        return fpersonfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fpersonfname
     *
     * @param fpersonfname the value for oa_notice_person.fpersonfname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFpersonfname(String fpersonfname) {
        this.fpersonfname = fpersonfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fmainid
     *
     * @return the value of oa_notice_person.fmainid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFmainid() {
        return fmainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fmainid
     *
     * @param fmainid the value for oa_notice_person.fmainid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFmainid(String fmainid) {
        this.fmainid = fmainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fbrowse
     *
     * @return the value of oa_notice_person.fbrowse
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFbrowse() {
        return fbrowse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fbrowse
     *
     * @param fbrowse the value for oa_notice_person.fbrowse
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFbrowse(String fbrowse) {
        this.fbrowse = fbrowse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fdeptname
     *
     * @return the value of oa_notice_person.fdeptname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFdeptname() {
        return fdeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fdeptname
     *
     * @param fdeptname the value for oa_notice_person.fdeptname
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFdeptname(String fdeptname) {
        this.fdeptname = fdeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.fdeptid
     *
     * @return the value of oa_notice_person.fdeptid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public String getFdeptid() {
        return fdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.fdeptid
     *
     * @param fdeptid the value for oa_notice_person.fdeptid
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setFdeptid(String fdeptid) {
        this.fdeptid = fdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_notice_person.version
     *
     * @return the value of oa_notice_person.version
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_notice_person.version
     *
     * @param version the value for oa_notice_person.version
     *
     * @mbg.generated Tue Mar 19 15:48:25 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}