package com.tlv8.oa.pojo;

import java.io.Serializable;
import java.util.Date;

public class OaPulicnotice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fognid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String fognid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fognname
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String fognname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.forgid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String forgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.forgname
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String forgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fcreateid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String fcreateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fcreatename
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String fcreatename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fcreatedatetime
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private Date fcreatedatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fpushdatetime
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private Date fpushdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.ftitle
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String ftitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fcontent
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String fcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fcreatedate
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private Date fcreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fpushid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String fpushid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fpushname
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String fpushname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.ftype
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String ftype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.fattfile
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private String fattfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_pulicnotice.version
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oa_pulicnotice
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fid
     *
     * @return the value of oa_pulicnotice.fid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fid
     *
     * @param fid the value for oa_pulicnotice.fid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fognid
     *
     * @return the value of oa_pulicnotice.fognid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getFognid() {
        return fognid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fognid
     *
     * @param fognid the value for oa_pulicnotice.fognid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFognid(String fognid) {
        this.fognid = fognid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fognname
     *
     * @return the value of oa_pulicnotice.fognname
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getFognname() {
        return fognname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fognname
     *
     * @param fognname the value for oa_pulicnotice.fognname
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFognname(String fognname) {
        this.fognname = fognname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.forgid
     *
     * @return the value of oa_pulicnotice.forgid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getForgid() {
        return forgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.forgid
     *
     * @param forgid the value for oa_pulicnotice.forgid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setForgid(String forgid) {
        this.forgid = forgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.forgname
     *
     * @return the value of oa_pulicnotice.forgname
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getForgname() {
        return forgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.forgname
     *
     * @param forgname the value for oa_pulicnotice.forgname
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setForgname(String forgname) {
        this.forgname = forgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fcreateid
     *
     * @return the value of oa_pulicnotice.fcreateid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getFcreateid() {
        return fcreateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fcreateid
     *
     * @param fcreateid the value for oa_pulicnotice.fcreateid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFcreateid(String fcreateid) {
        this.fcreateid = fcreateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fcreatename
     *
     * @return the value of oa_pulicnotice.fcreatename
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getFcreatename() {
        return fcreatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fcreatename
     *
     * @param fcreatename the value for oa_pulicnotice.fcreatename
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFcreatename(String fcreatename) {
        this.fcreatename = fcreatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fcreatedatetime
     *
     * @return the value of oa_pulicnotice.fcreatedatetime
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public Date getFcreatedatetime() {
        return fcreatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fcreatedatetime
     *
     * @param fcreatedatetime the value for oa_pulicnotice.fcreatedatetime
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFcreatedatetime(Date fcreatedatetime) {
        this.fcreatedatetime = fcreatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fpushdatetime
     *
     * @return the value of oa_pulicnotice.fpushdatetime
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public Date getFpushdatetime() {
        return fpushdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fpushdatetime
     *
     * @param fpushdatetime the value for oa_pulicnotice.fpushdatetime
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFpushdatetime(Date fpushdatetime) {
        this.fpushdatetime = fpushdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.ftitle
     *
     * @return the value of oa_pulicnotice.ftitle
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getFtitle() {
        return ftitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.ftitle
     *
     * @param ftitle the value for oa_pulicnotice.ftitle
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFtitle(String ftitle) {
        this.ftitle = ftitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fcontent
     *
     * @return the value of oa_pulicnotice.fcontent
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getFcontent() {
        return fcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fcontent
     *
     * @param fcontent the value for oa_pulicnotice.fcontent
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFcontent(String fcontent) {
        this.fcontent = fcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fcreatedate
     *
     * @return the value of oa_pulicnotice.fcreatedate
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public Date getFcreatedate() {
        return fcreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fcreatedate
     *
     * @param fcreatedate the value for oa_pulicnotice.fcreatedate
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFcreatedate(Date fcreatedate) {
        this.fcreatedate = fcreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fpushid
     *
     * @return the value of oa_pulicnotice.fpushid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getFpushid() {
        return fpushid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fpushid
     *
     * @param fpushid the value for oa_pulicnotice.fpushid
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFpushid(String fpushid) {
        this.fpushid = fpushid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fpushname
     *
     * @return the value of oa_pulicnotice.fpushname
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getFpushname() {
        return fpushname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fpushname
     *
     * @param fpushname the value for oa_pulicnotice.fpushname
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFpushname(String fpushname) {
        this.fpushname = fpushname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.ftype
     *
     * @return the value of oa_pulicnotice.ftype
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.ftype
     *
     * @param ftype the value for oa_pulicnotice.ftype
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFtype(String ftype) {
        this.ftype = ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.fattfile
     *
     * @return the value of oa_pulicnotice.fattfile
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public String getFattfile() {
        return fattfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.fattfile
     *
     * @param fattfile the value for oa_pulicnotice.fattfile
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setFattfile(String fattfile) {
        this.fattfile = fattfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_pulicnotice.version
     *
     * @return the value of oa_pulicnotice.version
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_pulicnotice.version
     *
     * @param version the value for oa_pulicnotice.version
     *
     * @mbg.generated Wed Mar 20 19:07:18 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}