package com.tlv8.system.pojo;

import java.io.Serializable;
import java.util.Date;

public class SaOprolemanagement implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanagement.sid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanagement.sorgid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String sorgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanagement.sorgname
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String sorgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanagement.sorgfid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String sorgfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanagement.sorgfname
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String sorgfname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanagement.sroleid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String sroleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanagement.screatorfid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String screatorfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanagement.screatorfname
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String screatorfname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanagement.screatetime
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private Date screatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanagement.version
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa_oprolemanagement
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanagement.sid
     *
     * @return the value of sa_oprolemanagement.sid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanagement.sid
     *
     * @param sid the value for sa_oprolemanagement.sid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanagement.sorgid
     *
     * @return the value of sa_oprolemanagement.sorgid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getSorgid() {
        return sorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanagement.sorgid
     *
     * @param sorgid the value for sa_oprolemanagement.sorgid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setSorgid(String sorgid) {
        this.sorgid = sorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanagement.sorgname
     *
     * @return the value of sa_oprolemanagement.sorgname
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getSorgname() {
        return sorgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanagement.sorgname
     *
     * @param sorgname the value for sa_oprolemanagement.sorgname
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setSorgname(String sorgname) {
        this.sorgname = sorgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanagement.sorgfid
     *
     * @return the value of sa_oprolemanagement.sorgfid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getSorgfid() {
        return sorgfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanagement.sorgfid
     *
     * @param sorgfid the value for sa_oprolemanagement.sorgfid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setSorgfid(String sorgfid) {
        this.sorgfid = sorgfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanagement.sorgfname
     *
     * @return the value of sa_oprolemanagement.sorgfname
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getSorgfname() {
        return sorgfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanagement.sorgfname
     *
     * @param sorgfname the value for sa_oprolemanagement.sorgfname
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setSorgfname(String sorgfname) {
        this.sorgfname = sorgfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanagement.sroleid
     *
     * @return the value of sa_oprolemanagement.sroleid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getSroleid() {
        return sroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanagement.sroleid
     *
     * @param sroleid the value for sa_oprolemanagement.sroleid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setSroleid(String sroleid) {
        this.sroleid = sroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanagement.screatorfid
     *
     * @return the value of sa_oprolemanagement.screatorfid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getScreatorfid() {
        return screatorfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanagement.screatorfid
     *
     * @param screatorfid the value for sa_oprolemanagement.screatorfid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setScreatorfid(String screatorfid) {
        this.screatorfid = screatorfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanagement.screatorfname
     *
     * @return the value of sa_oprolemanagement.screatorfname
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getScreatorfname() {
        return screatorfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanagement.screatorfname
     *
     * @param screatorfname the value for sa_oprolemanagement.screatorfname
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setScreatorfname(String screatorfname) {
        this.screatorfname = screatorfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanagement.screatetime
     *
     * @return the value of sa_oprolemanagement.screatetime
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public Date getScreatetime() {
        return screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanagement.screatetime
     *
     * @param screatetime the value for sa_oprolemanagement.screatetime
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setScreatetime(Date screatetime) {
        this.screatetime = screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanagement.version
     *
     * @return the value of sa_oprolemanagement.version
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanagement.version
     *
     * @param version the value for sa_oprolemanagement.version
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}