package com.tlv8.system.pojo;

import java.io.Serializable;
import java.util.Date;

public class SaOprolemanage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanage.sid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanage.sorgid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String sorgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanage.sorgfid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String sorgfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanage.spersonid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String spersonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanage.sroleid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String sroleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanage.screatorid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private String screatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanage.screatetime
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private Date screatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oprolemanage.version
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa_oprolemanage
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanage.sid
     *
     * @return the value of sa_oprolemanage.sid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanage.sid
     *
     * @param sid the value for sa_oprolemanage.sid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanage.sorgid
     *
     * @return the value of sa_oprolemanage.sorgid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getSorgid() {
        return sorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanage.sorgid
     *
     * @param sorgid the value for sa_oprolemanage.sorgid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setSorgid(String sorgid) {
        this.sorgid = sorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanage.sorgfid
     *
     * @return the value of sa_oprolemanage.sorgfid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getSorgfid() {
        return sorgfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanage.sorgfid
     *
     * @param sorgfid the value for sa_oprolemanage.sorgfid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setSorgfid(String sorgfid) {
        this.sorgfid = sorgfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanage.spersonid
     *
     * @return the value of sa_oprolemanage.spersonid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getSpersonid() {
        return spersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanage.spersonid
     *
     * @param spersonid the value for sa_oprolemanage.spersonid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setSpersonid(String spersonid) {
        this.spersonid = spersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanage.sroleid
     *
     * @return the value of sa_oprolemanage.sroleid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getSroleid() {
        return sroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanage.sroleid
     *
     * @param sroleid the value for sa_oprolemanage.sroleid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setSroleid(String sroleid) {
        this.sroleid = sroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanage.screatorid
     *
     * @return the value of sa_oprolemanage.screatorid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public String getScreatorid() {
        return screatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanage.screatorid
     *
     * @param screatorid the value for sa_oprolemanage.screatorid
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setScreatorid(String screatorid) {
        this.screatorid = screatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanage.screatetime
     *
     * @return the value of sa_oprolemanage.screatetime
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public Date getScreatetime() {
        return screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanage.screatetime
     *
     * @param screatetime the value for sa_oprolemanage.screatetime
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setScreatetime(Date screatetime) {
        this.screatetime = screatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oprolemanage.version
     *
     * @return the value of sa_oprolemanage.version
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oprolemanage.version
     *
     * @param version the value for sa_oprolemanage.version
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}