package com.tlv8.system.mapper;

import com.baomidou.dynamic.datasource.annotation.DS;
import com.tlv8.system.pojo.SaOprolemanage;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@DS("system")
@Mapper
public interface SaOprolemanageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_oprolemanage
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_oprolemanage
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    int insert(SaOprolemanage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_oprolemanage
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    SaOprolemanage selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_oprolemanage
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    List<SaOprolemanage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_oprolemanage
     *
     * @mbg.generated Sat Nov 23 20:12:46 CST 2024
     */
    int updateByPrimaryKey(SaOprolemanage row);
}